default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  host: db
  username: postgres
  password:
development:
  <<: *default
  database: bleater-dev



test:
  <<: *default
  database: bleater-test

production:
  <<: *default
  database: bleater
  username: bleater
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>